#pragma once
#include "CoreMinimal.h"
#include "ERivalsWindowCancelType.generated.h"

UENUM(BlueprintType)
enum class ERivalsWindowCancelType : uint8 {
    None,
    OnAnyHit,
    OnObjectHit,
    OnPlayerHit,
    OnShieldHit,
    OnGrab,
    OnDetect,
    OnCounter,
    OnThrow,
    Parried,
    Grounded,
    Aerial,
    UpDown,
    DownDown,
    ForwardDown,
    BackwardDown,
    JumpDown,
    JumpPressed,
    DoubleJumpPressed,
    AttackDown,
    AttackPressed,
    AttackReleased,
    StrongDown,
    StrongPressed,
    StrongReleased,
    SpecialDown,
    SpecialPressed,
    SpecialReleased,
    FstrongPressed,
    UstrongPressed,
    DstrongPressed,
    FspecialPressed,
    DspecialPressed,
    ShieldDown,
    ShieldPressed,
    ShieldReleased,
    TauntDown,
    TauntPressed,
    TauntReleased,
    StateInt0,
    StateInt1,
    StateInt2,
    CharacterSpecific1,
    CharacterSpecific2,
    CharacterSpecific3,
    CharacterSpecific4,
};

