#pragma once
#include "CoreMinimal.h"
#include "ERivalsCharacterAttack.generated.h"

UENUM(BlueprintType)
enum class ERivalsCharacterAttack : uint8 {
    None,
    Jab,
    DAttack,
    Ftilt,
    Utilt,
    Dtilt,
    FirstTiltAttack = Ftilt,
    LastTiltAttack = Dtilt,
    Fstrong,
    Ustrong,
    Dstrong,
    FirstStrongAttack = Fstrong,
    LastStrongAttack = Dstrong,
    Nair,
    Fair,
    Bair,
    Uair,
    Dair,
    FirstAerialAttack = Nair,
    LastAerialAttack = Dair,
    Nspecial,
    Fspecial,
    Uspecial,
    Dspecial,
    FirstSpecial = Nspecial,
    LastSpecial = Dspecial,
    NspecialAir,
    FspecialAir,
    UspecialAir,
    DspecialAir,
    FirstSpecialAir = NspecialAir,
    LastSpecialAir = DspecialAir,
    Grab,
    DashGrab,
    PivotGrab,
    FirstGrab = Grab,
    LastGrab = PivotGrab,
    Fthrow,
    Bthrow,
    Uthrow,
    Dthrow,
    FirstThrow = Fthrow,
    LastThrow = Dthrow,
    Pummel,
    PummelSpecial,
    FirstPummel = Pummel,
    LastPummel = PummelSpecial,
    GetupAttack,
    GetupSpecial,
    FirstGetupAttack = GetupAttack,
    LastGetupAttack = GetupSpecial,
    LedgeAttack,
    LedgeSpecial,
    FirstLedgeAttack = LedgeAttack,
    LastLedgeAttack = LedgeSpecial,
    Taunt1,
    Taunt2,
    Taunt3,
    Taunt4,
    FirstTaunt = Taunt1,
    LastTaunt = Taunt4,
    Extra1,
    Extra2,
    Extra3,
    Extra4,
    Intro,
    Thrown,
    Count,
};

