#pragma once
#include "CoreMinimal.h"
#include "InitialDataFetchingFirstStepFinishedDynamicMulticastDelegateDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FInitialDataFetchingFirstStepFinishedDynamicMulticastDelegate, bool, bWasSuccessful);

