#pragma once
#include "CoreMinimal.h"
#include "PlayFabLoginWithEmailAddressBeforeSteamLinkingAttemptSuccessDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FPlayFabLoginWithEmailAddressBeforeSteamLinkingAttemptSuccess, bool, bAlreadyHasSteamAccountLink);

